apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 823796879023.dkr.ecr.ap-northeast-2.amazonaws.com/project-cicd
  newName: 823796879023.dkr.ecr.ap-northeast-2.amazonaws.com/project-cicd
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
