apiVersion: v1
kind: Service
metadata:
  name: project
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  selector:
    app: project
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
